### ISSUE TITLE
[Typo] Preciser que c'est le software qui importe pour la compilation

### ISSUE THREAD

**Issue by Wateir** [PapillonApp/docs#4]
[Dans Compiler pour IOS](https://github.com/PapillonApp/docs/blob/gitbook/develop/build/pour-ios.md)

Remplacer `Pour compiler Papillon pour iOS, vous devez posséder un Mac.` 
par `Pour compiler Papillon pour iOS, vous devez être sur MacOS`

Meme si la difference est infime, on ouvre la porte au hackintosh par exemple, et ferme la porte au mac intel sur linux aussi

**Comment by Clmnnt** [comment]
good du coup
